import type { Project } from '../types';

export const PROJECTS: Project[] = [
  {
    id: 24,
    title: 'Nansen IoT',
    tag: '_nansen-iot',
    description: 'Plataforma de monitoramento industrial IoT e gestao de energia com dashboards em tempo real.',
    details: 'Plataforma de gestao industrial IoT para monitoramento de equipamentos, linhas de producao e consumo energetico. Modulos:\n\n- Dashboard principal com metricas em tempo real\n- Gestao de produtos, equipamentos e setores produtivos\n- Registro e monitoramento de dispositivos IoT (NansenIC, NansenSensor)\n- Gerenciamento de linhas de producao\n- Faturamento energetico com dashboards comparativos e analise de consumo\n- Sistema de missoes com dashboard dedicado\n- Gestao de usuarios com controle de acesso\n- Internacionalizacao (i18n) multi-idioma\n- Loja integrada e sistema de quizzes',
    image: '/projects/nansen-login.png',
    images: [
      '/projects/nansen-login.png',
      '/projects/nansen-home.png',
      '/projects/nansen-missoes.png',
      '/projects/nansen-dashboard.png',
      '/projects/nansen-faturamento.png',
      '/projects/nansen-missoes-lista.png',
    ],
    technologies: ['React', 'TypeScript', 'Tailwind', 'Vite', 'Ant Design', 'Zustand', 'Recharts', 'Axios', 'React Hook Form', 'React Router', 'React Toastify', 'Framer Motion'],
    repoUrl: 'https://github.com/Nansen-NGE/NansenWeb',
    isPrivate: true,
  },
  {
    id: 25,
    title: 'IA-FogoBio',
    tag: '_ia-fogobio',
    description: 'Plataforma de deteccao e monitoramento de focos de incendio com IA e dados de satelite NASA.',
    details: 'Plataforma de inteligencia para deteccao e monitoramento de focos de incendio utilizando dados de satelite NASA FIRMS (VIIRS - NOAA-20, NOAA-21, SNPP). Tres componentes:\n\n- Frontend: mapa interativo com MapLibre GL, modulos de Planejamento, Monitoramento e Previsao. Camadas de tipos de solo, predicao ML (accuracy > 94.3%), focos de incendio e NDVI vegetacao. Sidebar com ferramentas, filtros e dados. Temas claro/escuro, bandeiras PT/EN/ES, exportacao CSV/Excel. Status bar com coordenadas, escala, fonte INPE/NASA e timestamp do ML.\n\n- Backend API (FastAPI): pipeline ETL para extracao, transformacao e carga de dados FIRMS. PostgreSQL com SQLAlchemy, processamento com Pandas/NumPy, clustering de focos.\n\n- Modulo ML: modelo de predicao de incendios com Scikit-learn, previsao de 7-14 dias, deteccao de areas de risco por bioma e tipo de solo.',
    image: '/projects/biofogo-mapa.png',
    images: [
      '/projects/biofogo-mapa.png',
      '/projects/biofogo-previsao.png',
      '/projects/biofogo-monitoramento.png',
      '/projects/biofogo-dark.png',
      '/projects/biofogo-camadas.png',
      '/projects/biofogo-status.png',
    ],
    technologies: ['React', 'TypeScript', 'Tailwind', 'Vite', 'shadcn/ui', 'MapLibre GL', 'Recharts', 'React Hook Form', 'FastAPI', 'Python', 'PostgreSQL'],
    repoUrl: 'https://github.com/IA-FogoBio-IFAM/biofogo-ia',
    isPrivate: true,
  },
  {
    id: 4,
    title: 'Prototipo Yamaha',
    tag: '_prototipo-yamaha',
    description: 'Prototipo de interface com React usando PrimeReact, Ant Design e graficos interativos.',
    details: 'Prototipo de dashboard industrial para gestao de equipamentos e inspecoes. Modulos de: cadastro e listagem de equipamentos, registro de inspecoes com formularios complexos, dashboard com graficos interativos, sistema de login. Construido com tres bibliotecas de UI (PrimeReact, Ant Design, shadcn/ui), internacionalizacao com i18next e animacoes com Framer Motion.',
    image: '/projects/yamaha-dashboard.png',
    images: ['/projects/yamaha-dashboard.png'],
    technologies: ['React', 'Tailwind', 'TypeScript', 'Vite', 'shadcn/ui', 'PrimeReact', 'Ant Design', 'Zustand', 'Recharts', 'Axios', 'React Toastify', 'Framer Motion'],
    repoUrl: 'https://github.com/DevAlissu/prototipo-yamaha',
    liveUrl: 'https://prototipo-yamaha.vercel.app',
  },
  {
    id: 15,
    title: 'Microsservico SEFAZ',
    tag: '_ms-sefaz',
    description: 'Microsservico de integracao com a SEFAZ para consulta e gestao de NF-e.',
    details: 'Microsservico Python com FastAPI para integracao completa com a SEFAZ. Tres modulos de endpoints:\n\n- SefazNFe-Completo: consulta NF-e completa com salvamento em multiplas tabelas, parsing de XML, download de XML e DANFE (PDF), status do servico e estatisticas do banco.\n\n- SefazNFe-Compativel: versao simplificada para consulta e teste de extracao de dados, download de XML/DANFE e teste de salvamento em banco.\n\n- Scheduler-Automacao: agendamento automatico de consultas via NSU, forcamento de consulta imediata, manifestacao de ciencia de operacao de NF-e.\n\nAutenticacao com certificados digitais PKCS12, validacao com Pydantic, servidor ASGI com Uvicorn. Deploy isolado via Docker como parte do ecossistema Sistema Melo.',
    image: '/projects/ms-sefaz.png',
    technologies: ['FastAPI', 'Python'],
    repoUrl: 'https://github.com/Sistema-Melo/microsservice_sefaz',
    isPrivate: true,
  },
  {
    id: 5,
    title: 'Sprint Tools',
    tag: '_sprint-tools',
    description: 'Ferramenta de gestao de sprints com retrospectiva, timer e board colaborativo.',
    details: 'Ferramenta de gestao agil com board de retrospectiva colaborativo em tempo real. Colunas configuradas: "O que foi legal", "O que poderia ter sido melhor", "Sugestoes de melhoria", "O que devemos manter", "O que devemos abandonar" e "Reconhecimento". Funcionalidades de: adicionar cards anonimos, timer de sessao, revelar cards simultaneamente, resetar board. Sistema multi-usuario com contagem de participantes online.',
    image: '/projects/sprint-tools-1.png',
    images: ['/projects/sprint-tools-1.png'],
    technologies: ['React', 'Tailwind', 'TypeScript', 'Vite', 'Zustand', 'React Router'],
    repoUrl: 'https://github.com/DevAlissu/sprint-tools',
    liveUrl: 'http://sprintpoker.duckdns.org:8000',
    isPrivate: true,
  },
  {
    id: 1,
    title: 'CodeBot SaaS',
    tag: '_codebot-saas',
    description: 'Plataforma SaaS de code review automatizado com IA para equipes via Discord.',
    details: 'Plataforma SaaS multi-tenant de code review automatizado com IA. Monorepo Turborepo com 4 pacotes:\n\n- API (Fastify + Drizzle ORM + PostgreSQL): rotas de auth, tenants, webhooks GitHub, estatisticas de reviews e configuracoes. Schema com planos (starter/pro/enterprise), niveis de rigor de review (relaxed/normal/strict), guias de review por tipo (frontend/backend/mobile) e tracking de tokens de IA.\n\n- Painel Web (React + Vite): login com OAuth Discord/GitHub, dashboard de metricas de PRs revisados, gerenciamento de equipe e membros, configuracao de guias de review e settings do bot.\n\n- Bot Discord: revisor de codigo automatico que analisa PRs, respeita personalidade configuravel, limite de respostas por thread, VIP users e senior authors.\n\n- Shared: tipos e utilidades compartilhados entre pacotes.\n\nAutenticacao OAuth2 via Arctic com sessoes seguras via Oslo.',
    image: '/projects/codebot-saas.png',
    technologies: ['React', 'Tailwind', 'TypeScript', 'Vite', 'Fastify', 'Drizzle', 'PostgreSQL', 'Node.js'],
    repoUrl: 'https://github.com/DevAlissu/codebot-saas',
    isPrivate: true,
  },
  {
    id: 10,
    title: 'Emprestimo Mobile',
    tag: '_emprestimo-mobile',
    description: 'App mobile do IFAM para gestao de emprestimo de equipamentos com React Native.',
    details: 'Aplicativo mobile institucional do IFAM para gestao de emprestimo de equipamentos (notebooks, projetores, cabos HDMI). Modulos:\n\n- Novo Emprestimo: busca de equipamentos por nome ou patrimonio, filtros por categoria (Notebooks, Projetores, Cabos), selecao de equipamentos disponiveis com status em tempo real.\n\n- Meus Emprestimos: visualizacao e gerenciamento de emprestimos ativos, historico completo.\n\n- Emprestimos Pendentes: fila de liberacao de retirada para funcionarios, busca por ID/professor/SIAPE, tempo de espera, botao de liberar retirada.\n\nNavegacao por tabs (Inicio, Sistemas, Sobre), sidebar com menu lateral.',
    image: '/projects/emprestimo-1.jpg',
    images: [
      '/projects/emprestimo-1.jpg',
      '/projects/emprestimo-2.jpg',
      '/projects/emprestimo-3.jpg',
      '/projects/emprestimo-4.jpg',
      '/projects/emprestimo-5.jpg',
      '/projects/emprestimo-6.jpg',
      '/projects/emprestimo-7.jpg',
      '/projects/emprestimo-8.jpg',
      '/projects/emprestimo-9.jpg',
      '/projects/emprestimo-10.jpg',
      '/projects/emprestimo-11.jpg',
    ],
    technologies: ['React Native', 'TypeScript'],
    repoUrl: 'https://github.com/DevAlissu/Emprestimo_mobile',
  },
  {
    id: 8,
    title: 'Clone ALEAM',
    tag: '_clone-aleam',
    description: 'Clone institucional da Assembleia Legislativa do AM com acessibilidade.',
    details: 'Recriacao do portal da Assembleia Legislativa do Amazonas com foco em acessibilidade (integracao VLibras). Paginas de: home institucional, CEAP (cota parlamentar) com tabelas e filtros, vencimentos com graficos Recharts. Notificacoes com React Toastify, animacoes com Framer Motion e estado com Zustand.',
    image: '/projects/aleam-ceap.png',
    images: [
      '/projects/aleam-ceap.png',
      '/projects/aleam-home.png',
      '/projects/aleam-vlibras.png',
      '/projects/aleam-gastos.png',
      '/projects/aleam-vencimentos.png',
      '/projects/aleam-csv.png',
    ],
    technologies: ['React', 'TypeScript', 'Vite', 'Zustand', 'Recharts', 'Axios', 'React Toastify', 'Framer Motion'],
    repoUrl: 'https://github.com/DevAlissu/clone_ALEAM',
    liveUrl: 'https://clone-aleam.vercel.app',
    isPrivate: true,
  },
  {
    id: 18,
    title: 'Cilada',
    tag: '_cilada',
    description: 'Aplicacao web interativa desenvolvida com JavaScript, CSS e HTML.',
    image: '',
    technologies: ['JavaScript'],
    repoUrl: 'https://github.com/DevAlissu/Cilada',
    liveUrl: 'https://cilada.vercel.app',
  },
  {
    id: 2,
    title: 'Sistema Melo',
    tag: '_sistema-melo',
    description: 'Sistema corporativo com Next.js, autenticacao, relatorios PDF/Excel e multiplos bancos.',
    details: 'ERP corporativo completo com modulos de: cadastros (clientes, fornecedores, produtos, marcas, bancos, vendedores), financeiro (contas a pagar/receber, faturamento, transferencias), compras (nova compra, historico, dashboard), estoque, vendas e relatorios. Controle de acesso por filiais com grupos de permissoes e perfis. Geracao de relatorios em PDF e Excel. Integracao dual-database com PostgreSQL (Sequelize + Prisma) e Oracle. Multi-filial com selecao de filial no login.',
    image: '/projects/sistema-melo.png',
    images: [
      '/projects/sistema-melo.png',
      '/projects/melo-vendas.png',
      '/projects/melo-contas.png',
    ],
    technologies: ['React', 'Next.js', 'Tailwind', 'TypeScript', 'shadcn/ui', 'Axios', 'React Hook Form', 'Framer Motion', 'Prisma', 'Sequelize', 'PostgreSQL', 'Node.js'],
    repoUrl: 'https://github.com/DevAlissu/Sistema_Melo',
    isPrivate: true,
  },
  {
    id: 16,
    title: 'Jungle Logic',
    tag: '_jungle-logic',
    description: 'App educativo mobile com React Native e Expo para aprender jogando.',
    details: 'Aplicativo mobile educativo com tematica de selva. Telas de: boas-vindas com ilustracoes 3D, selecao de personagem e sistema de coletaveis. Construido com React Native e Expo, navegacao entre telas e componentes customizados.',
    image: '/projects/jungle-logic.jpg',
    technologies: ['React Native', 'JavaScript'],
    repoUrl: 'https://github.com/DevAlissu/Jungle-Logic',
  },
  {
    id: 6,
    title: 'Drawnomes',
    tag: '_drawnomes',
    description: 'Plataforma de sorteio de nomes e amigo secreto com lista de desejos e chat em grupo.',
    details: 'Plataforma completa de sorteio de nomes para celebracoes (Pascoa, Natal, Aniversario, Dia dos Namorados, Ano Novo). Fluxo guiado em 8 passos:\n\n1. Identificacao do organizador\n2. Adicionar participantes\n3. Selecao do tipo de celebracao\n4. Definir data do evento\n5. Definir valor sugerido de presente (R$25 a R$100)\n6. Mensagem personalizada para o grupo\n7. Revisao e criacao\n8. Sorteio automatico\n\nFuncionalidades pos-sorteio: painel da celebracao com membros, lista de desejos com imagens de presentes, localizador de presentes por genero/idade, chat em grupo em tempo real, compartilhamento por link de convite, confirmacao de participantes.',
    image: '/projects/drawnomes-home.png',
    images: [
      '/projects/drawnomes-home.png',
      '/projects/drawnomes-passo1.png',
      '/projects/drawnomes-passo1b.png',
      '/projects/drawnomes-passo2.png',
      '/projects/drawnomes-passo4.png',
      '/projects/drawnomes-passo5.png',
      '/projects/drawnomes-passo6.png',
      '/projects/drawnomes-passo7.png',
      '/projects/drawnomes-celebracao.png',
      '/projects/drawnomes-sorteio.png',
      '/projects/drawnomes-resultado.png',
    ],
    technologies: ['React', 'Tailwind', 'TypeScript', 'Vite', 'shadcn/ui', 'Zustand', 'React Query', 'Recharts', 'React Hook Form', 'Axios', 'React Router'],
    repoUrl: 'https://github.com/DevAlissu/drawnomes',
    liveUrl: 'https://drawnomes.online',
    isPrivate: true,
  },
  {
    id: 26,
    title: 'Horto App',
    tag: '_horto-app',
    description: 'App mobile de adocao e cuidado de mudas nativas do Amazonas com identificacao por IA.',
    details: 'Aplicativo mobile para o Horto Municipal de Manaus, desenvolvido com Flutter. Funcionalidades:\n\n- Onboarding ilustrado: adote mudas, diversidade de especies nativas (Assistacia, Acerola, Boldo, Pupunha), gerenciamento de mudas adotadas, identificacao de plantas por camera.\n\n- Cadastro personalizado com mascote "Protinho".\n\n- Catalogo de mudas por categoria: Ornamentais (Coleus, Beldroega), Frutiferas, Medicinais, com fotos reais das plantas.\n\n- Sistema de adocao com controle de tempo e quantidade.\n\n- Identificacao de plantas via camera do celular usando visao computacional (modelo treinado com Python/TensorFlow).\n\n- Gestao de plantas adotadas com descricao e acompanhamento.',
    image: '/projects/horto-catalogo.png',
    images: [
      '/projects/horto-catalogo.png',
      '/projects/horto-adote.png',
      '/projects/horto-mudas.png',
      '/projects/horto-gerencie.png',
      '/projects/horto-camera.png',
      '/projects/horto-ola.png',
      '/projects/horto-nome.png',
      '/projects/horto-protinho.png',
      '/projects/horto-home.png',
    ],
    technologies: ['Flutter', 'Python'],
    repoUrl: 'https://github.com/DevAlissu/horto-app',
    isPrivate: true,
  },
  {
    id: 7,
    title: 'Wappy2 PPV',
    tag: '_wappy2-ppv',
    description: 'Aplicacao web com PrimeReact, Supabase e animacoes com Framer Motion.',
    details: 'Aplicacao web com backend Supabase (autenticacao, banco e storage), interface construida com PrimeReact e Styled Components. Rotas protegidas, animacoes de transicao com Framer Motion, gerenciamento de estado com Zustand e consumo de APIs com Axios.',
    image: '',
    technologies: ['React', 'Tailwind', 'JavaScript', 'PrimeReact', 'Styled Components', 'Zustand', 'Supabase', 'Axios', 'Framer Motion'],
    repoUrl: 'https://github.com/DevAlissu/wappy2_ppv',
    isPrivate: true,
  },
  {
    id: 9,
    title: 'Bot Discord',
    tag: '_bot-discord',
    description: 'Bot Discord multi-modulo com IA Gemini, GitHub, Jira e Google Calendar.',
    details: 'Bot Discord corporativo com arquitetura modular:\n\n- Modulo Gemini: chat com IA Google Gemini para respostas inteligentes e contextuais.\n\n- Modulo GitHub: revisao automatica de PRs, formatacao de diffs, lembretes de reviews pendentes, autenticacao via GitHub App.\n\n- Modulo Jira: integracao com Jira para consulta e gestao de tickets diretamente no Discord.\n\n- Modulo Calendar: integracao com Google Calendar, configuracao de equipes e agendamentos.\n\n- Modulo Webhook: servidor Express embutido para receber webhooks externos.\n\n- Comandos: /alertas, /meet, /ping, /rank, /rankcard, /rankcommit, /rankreview.\n\nLoader automatico de comandos e eventos, autenticacao JWT e Google Auth.',
    image: '',
    technologies: ['Node.js', 'JavaScript'],
    repoUrl: 'https://github.com/DevAlissu/bot-discord',
    isPrivate: true,
  },
  {
    id: 3,
    title: 'Zilia Front Refactor',
    tag: '_zilia-refactor',
    description: 'Refatoracao do frontend com Next.js e backend Django, integrado a SQL Server e PostgreSQL.',
    details: 'Refatoracao completa de sistema de medicao optica. Frontend Next.js 14 com modulos de: medicao automatica de stencil, cadastro de usuarios, relatorios de compliance, configuracoes e progresso. Backend Django REST Framework com integracao OpenCV para processamento de imagens, dual-database (PostgreSQL + SQL Server via ODBC). Dashboards com Recharts e Chart.js. Deploy com Docker e Gunicorn.',
    image: '',
    technologies: ['React', 'Next.js', 'Tailwind', 'TypeScript', 'shadcn/ui', 'Styled Components', 'Axios', 'React Hook Form', 'Recharts', 'Chart.js', 'Django', 'Python', 'PostgreSQL', 'SQL Server'],
    repoUrl: 'https://github.com/DevAlissu/Zilia_FrontRefactor',
  },
  {
    id: 11,
    title: 'React Native Login',
    tag: '_rn-login',
    description: 'Layout de tela de login desenvolvido com React Native.',
    image: '',
    technologies: ['React Native', 'JavaScript'],
    repoUrl: 'https://github.com/DevAlissu/react-native-login',
  },
  {
    id: 12,
    title: 'LSE IA',
    tag: '_lse-ia',
    description: 'Rede neural para reconhecimento de Lingua de Sinais com Python e visao computacional.',
    image: '',
    technologies: ['Python'],
    repoUrl: 'https://github.com/DevAlissu/LSE_IA_Fork',
  },
  {
    id: 13,
    title: 'Angular Contatos',
    tag: '_angular-contatos',
    description: 'Aplicativo de lista de contatos desenvolvido com Angular.',
    image: '',
    technologies: ['Angular', 'TypeScript'],
    repoUrl: 'https://github.com/DevAlissu/angular-lista-de-contatos',
  },
  {
    id: 17,
    title: 'ProgVark',
    tag: '_progvark',
    description: 'Projeto academico de programacao desenvolvido em Java.',
    image: '',
    technologies: ['Java'],
    repoUrl: 'https://github.com/DevAlissu/ProgVark',
    isPrivate: true,
  },
  {
    id: 19,
    title: 'Hands-On DevTITANS',
    tag: '_hands-on-devtitans',
    description: 'Projeto final em C++ do programa DevTITANS com foco em sistemas embarcados.',
    image: '',
    technologies: ['C++'],
    repoUrl: 'https://github.com/DevAlissu/Hands-On_Final_Equipe_1',
  },
  {
    id: 20,
    title: 'Saci Jumper',
    tag: '_saci-jumper',
    description: 'Jogo de plataforma desenvolvido em Java.',
    image: '',
    technologies: ['Java'],
    repoUrl: 'https://github.com/DevAlissu/Saci-Jumper',
  },
  {
    id: 21,
    title: 'Rula Tronco',
    tag: '_rula-tronco',
    description: 'Ferramenta de analise ergonomica RULA desenvolvida em Python.',
    image: '',
    technologies: ['Python'],
    repoUrl: 'https://github.com/DevAlissu/Rula_tronco',
  },
  {
    id: 22,
    title: 'Perceptron',
    tag: '_perceptron',
    description: 'Rede Neural Artificial de camada unica, Perceptron, implementada em Python.',
    image: '',
    technologies: ['Python'],
    repoUrl: 'https://github.com/DevAlissu/Perceptron',
  },
  {
    id: 14,
    title: 'Al Virtual Mouse',
    tag: '_virtual-mouse',
    description: 'Sistema de controle de cursor por IA usando Python e OpenCV em tempo real.',
    image: '',
    technologies: ['Python'],
    repoUrl: 'https://github.com/DevAlissu/Al-Virtual-Mouse',
  },
];

export interface TechSubCategory {
  label: string;
  iconColor: string;
  techs: string[];
}

export interface TechCategory {
  label: string;
  iconColor: string;
  subCategories: TechSubCategory[];
}

export const TECH_CATEGORIES: TechCategory[] = [
  {
    label: 'frontend',
    iconColor: '#ad46ff',
    subCategories: [
      {
        label: 'frameworks',
        iconColor: '#61DAFB',
        techs: ['React', 'Next.js', 'React Native', 'Vue', 'Angular', 'Flutter'],
      },
      {
        label: 'ui-libs',
        iconColor: '#9d4edd',
        techs: ['shadcn/ui', 'PrimeReact', 'Ant Design'],
      },
      {
        label: 'styling',
        iconColor: '#06B6D4',
        techs: ['Tailwind', 'Styled Components'],
      },
      {
        label: 'state',
        iconColor: '#43D9AD',
        techs: ['Zustand'],
      },
      {
        label: 'data-fetching',
        iconColor: '#ffb86a',
        techs: ['Axios', 'React Query', 'Supabase'],
      },
      {
        label: 'forms',
        iconColor: '#ffa1ad',
        techs: ['React Hook Form'],
      },
      {
        label: 'routing',
        iconColor: '#f44250',
        techs: ['React Router'],
      },
      {
        label: 'charts',
        iconColor: '#8884d8',
        techs: ['Recharts', 'Chart.js'],
      },
      {
        label: 'mapas',
        iconColor: '#4264FB',
        techs: ['MapLibre GL'],
      },
      {
        label: 'ui-utils',
        iconColor: '#90a1b9',
        techs: ['Framer Motion', 'React Toastify'],
      },
      {
        label: 'bundler',
        iconColor: '#646CFF',
        techs: ['Vite'],
      },
    ],
  },
  {
    label: 'backend',
    iconColor: '#43D9AD',
    subCategories: [
      {
        label: 'frameworks',
        iconColor: '#339933',
        techs: ['Node.js', 'Fastify', 'FastAPI', 'Django'],
      },
      {
        label: 'orms',
        iconColor: '#C5F74F',
        techs: ['Drizzle', 'Prisma', 'Sequelize'],
      },
    ],
  },
  {
    label: 'databases',
    iconColor: '#ffb86a',
    subCategories: [
      {
        label: 'sql',
        iconColor: '#336791',
        techs: ['PostgreSQL', 'SQL Server'],
      },
    ],
  },
  {
    label: 'languages',
    iconColor: '#ffa1ad',
    subCategories: [
      {
        label: 'all',
        iconColor: '#ffa1ad',
        techs: ['TypeScript', 'JavaScript', 'Python', 'Java', 'C++'],
      },
    ],
  },
];

export const ALL_TECHNOLOGIES = TECH_CATEGORIES.flatMap((c) =>
  c.subCategories.flatMap((s) => s.techs),
);
